# pytest.ini
[pytest]
python_files = *_tests.py test_*.py  # Это мы добавили в предыдущем шаге
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*            # Устанавливает правила для имен функций

markers=
    ui: Маркировка для   UI тестов.
    smoke: Маркировка для  smoke  тестов.
    regression: Маркировка для   regression тестов.
    registration: Маркировка для   registration  тестов.
    authorization: Маркировка для   authorization  тестов.